#
# Copyright (c) 2020 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable SDK
CONFIG_LMTSDK=y

# General config
CONFIG_MAIN_STACK_SIZE=1024

## Power management
CONFIG_PM_DEVICE=y

# WDT
CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=y

# Firmware version string
CONFIG_MCUBOOT_IMGTOOL_SIGN_VERSION="0.1.0"
