/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SRC_A2_PB_H_INCLUDED
#define PB_SRC_A2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _UplinkEventType {
    UplinkEventType_NO_EVENT = 0,
    UplinkEventType_LOG_SENT = 1,
    UplinkEventType_FIRMWARE_UPGRADED = 2,
    UplinkEventType_TERMINAL_OK = 3,
    UplinkEventType_TERMINAL_FAILED = 4,
    UplinkEventType_FIRMWARE_UPGRADE_FAILED = 5
} UplinkEventType;

typedef enum _DownlinkActionType {
    DownlinkActionType_NO_ACTION = 0,
    DownlinkActionType_LOG_REQUEST = 1,
    DownlinkActionType_FIRMWARE_UPDATE = 2,
    DownlinkActionType_COMMAND = 3
} DownlinkActionType;

/* Struct definitions */
typedef struct _Period {
    uint64_t Timestamp; /* Timestamp of the period change */
    uint32_t Value; /* Period value */
    uint32_t Cindex; /* Index value for the 1st measurement column */
} Period;

typedef struct _Column {
    int32_t Track[12]; /* Array for storing different sensor data */
} Column;

typedef struct _Data {
    pb_size_t Periods_count;
    Period Periods[3]; /* Array for storing periods */
    pb_size_t Columns_count;
    Column Columns[50]; /* Array for storing measurement sets */
} Data;

typedef struct _Network {
    int32_t RSRP;
    int32_t RSRQ;
    int32_t SNR;
} Network;

typedef struct _UplinkEvent {
    UplinkEventType Event;
    uint64_t EventTimestamp;
} UplinkEvent;

typedef struct _Uplink {
    uint64_t Timestamp;
    Data Tape[1];
    pb_size_t Connection_count;
    Network Connection[1];
    UplinkEvent UplinkEvents[1];
} Uplink;

typedef struct _Downlink {
    DownlinkActionType Action;
    char ActionParameters[256];
} Downlink;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _UplinkEventType_MIN UplinkEventType_NO_EVENT
#define _UplinkEventType_MAX UplinkEventType_TERMINAL_FAILED
#define _UplinkEventType_ARRAYSIZE ((UplinkEventType)(UplinkEventType_TERMINAL_FAILED+1))

#define _DownlinkActionType_MIN DownlinkActionType_NO_ACTION
#define _DownlinkActionType_MAX DownlinkActionType_COMMAND
#define _DownlinkActionType_ARRAYSIZE ((DownlinkActionType)(DownlinkActionType_COMMAND+1))





#define UplinkEvent_Event_ENUMTYPE UplinkEventType


#define Downlink_Action_ENUMTYPE DownlinkActionType


/* Initializer values for message structs */
#define Period_init_default                      {0, 0, 0}
#define Column_init_default                      {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define Data_init_default                        {0, {Period_init_default, Period_init_default, Period_init_default}, 0, {Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default, Column_init_default}}
#define Network_init_default                     {0, 0, 0}
#define UplinkEvent_init_default                 {_UplinkEventType_MIN, 0}
#define Uplink_init_default                      {0, {Data_init_default}, 0, {Network_init_default}, {UplinkEvent_init_default}}
#define Downlink_init_default                    {_DownlinkActionType_MIN, ""}
#define Period_init_zero                         {0, 0, 0}
#define Column_init_zero                         {{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define Data_init_zero                           {0, {Period_init_zero, Period_init_zero, Period_init_zero}, 0, {Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero, Column_init_zero}}
#define Network_init_zero                        {0, 0, 0}
#define UplinkEvent_init_zero                    {_UplinkEventType_MIN, 0}
#define Uplink_init_zero                         {0, {Data_init_zero}, 0, {Network_init_zero}, {UplinkEvent_init_zero}}
#define Downlink_init_zero                       {_DownlinkActionType_MIN, ""}

/* Field tags (for use in manual encoding/decoding) */
#define Period_Timestamp_tag                     1
#define Period_Value_tag                         2
#define Period_Cindex_tag                        3
#define Column_Track_tag                         1
#define Data_Periods_tag                         1
#define Data_Columns_tag                         2
#define Network_RSRP_tag                         1
#define Network_RSRQ_tag                         2
#define Network_SNR_tag                          3
#define UplinkEvent_Event_tag                    1
#define UplinkEvent_EventTimestamp_tag           2
#define Uplink_Timestamp_tag                     1
#define Uplink_Tape_tag                          2
#define Uplink_Connection_tag                    3
#define Uplink_UplinkEvents_tag                  4
#define Downlink_Action_tag                      1
#define Downlink_ActionParameters_tag            2

/* Struct field encoding specification for nanopb */
#define Period_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   Timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   Value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   Cindex,            3)
#define Period_CALLBACK NULL
#define Period_DEFAULT NULL

#define Column_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, INT32,    Track,             1)
#define Column_CALLBACK NULL
#define Column_DEFAULT NULL

#define Data_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  Periods,           1) \
X(a, STATIC,   REPEATED, MESSAGE,  Columns,           2)
#define Data_CALLBACK NULL
#define Data_DEFAULT NULL
#define Data_Periods_MSGTYPE Period
#define Data_Columns_MSGTYPE Column

#define Network_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    RSRP,              1) \
X(a, STATIC,   SINGULAR, INT32,    RSRQ,              2) \
X(a, STATIC,   SINGULAR, INT32,    SNR,               3)
#define Network_CALLBACK NULL
#define Network_DEFAULT NULL

#define UplinkEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    Event,             1) \
X(a, STATIC,   SINGULAR, UINT64,   EventTimestamp,    2)
#define UplinkEvent_CALLBACK NULL
#define UplinkEvent_DEFAULT NULL

#define Uplink_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   Timestamp,         1) \
X(a, STATIC,   FIXARRAY, MESSAGE,  Tape,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  Connection,        3) \
X(a, STATIC,   FIXARRAY, MESSAGE,  UplinkEvents,      4)
#define Uplink_CALLBACK NULL
#define Uplink_DEFAULT NULL
#define Uplink_Tape_MSGTYPE Data
#define Uplink_Connection_MSGTYPE Network
#define Uplink_UplinkEvents_MSGTYPE UplinkEvent

#define Downlink_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    Action,            1) \
X(a, STATIC,   SINGULAR, STRING,   ActionParameters,   2)
#define Downlink_CALLBACK NULL
#define Downlink_DEFAULT NULL

extern const pb_msgdesc_t Period_msg;
extern const pb_msgdesc_t Column_msg;
extern const pb_msgdesc_t Data_msg;
extern const pb_msgdesc_t Network_msg;
extern const pb_msgdesc_t UplinkEvent_msg;
extern const pb_msgdesc_t Uplink_msg;
extern const pb_msgdesc_t Downlink_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Period_fields &Period_msg
#define Column_fields &Column_msg
#define Data_fields &Data_msg
#define Network_fields &Network_msg
#define UplinkEvent_fields &UplinkEvent_msg
#define Uplink_fields &Uplink_msg
#define Downlink_fields &Downlink_msg

/* Maximum encoded size of messages (where known) */
#define Column_size                              132
#define Data_size                                6825
#define Downlink_size                            260
#define Network_size                             33
#define Period_size                              23
#define UplinkEvent_size                         13
#define Uplink_size                              6892

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
